### ISSUE TITLE
图叨叨不可用6.9.5

### ISSUE THREAD

**Issue by clsddy** [Xposed-Modules-Repo/top.hookvip.pro#1]
![Screenshot_2024-12-18-00-40-28-898_com.lcw.daodaopic.jpg](https://github.com/user-attachments/assets/3ef0838a-b804-47b2-b5ad-fbe22d2aaa80)

**Comment by lovejiuwu** [comment]
已收到反馈

**Comment by lovejiuwu** [comment]
已修复 请等待405正式版本更新

**Comment by clsddy** [comment]
6.9.6可用吗，好像又更新了🌚🌚

**Comment by lovejiuwu** [comment]
通杀

**Comment by clsddy** [comment]
> 杀完了吗,礼貌催更

**Comment by clsddy** [comment]
> 通杀

图叨叨不可用7.1.0
