### ISSUE TITLE
tiktok

### ISSUE THREAD

**Issue by gg-top-404** [Xposed-Modules-Repo/top.hookvip.pro#3]
### ⚠️ 重要阅读

- [X] 由于个人时间精力有限 不会采纳所有的适配请求 具体更新请以最新版为准
- [X] 可以提旧版模块上有的功能 会优先同步到新版模块
- [X] 请勿提出任何一个APP的去广告功能 推荐使用模块 [@AdClose](https://github.com/zjyzip/AdClose)
- [X] 提交应用前请动脑 你的需求是否合理 不要提出无理要求
- [x] 不再提供微信功能 请不要再询问

### 应用名称

tiktok

### 应用包名

com.zhiliaoapp.musically

### 应用用途

模拟国外卡环境

### 应用需求

```text
大佬，能适配一下tiktok嘛，模拟手机卡是外卡的环境，就像guise里面的sim卡模拟一样，guise已经停更了，不知道能用多久，guise1.1.1里面的sim卡模拟
```

### 应用下载地址/安装包

https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically

**Comment by lovejiuwu** [comment]
大可放心使用 guise就算停更 大概率也不会失效的 他是基于系统底层的hook hookvip暂时不考虑做这个功能
