### ISSUE TITLE
【BUG反馈】 Fake Location 1.3.5 BETA 1598版本已失效

### ISSUE THREAD

**Issue by XZH2024** [Xposed-Modules-Repo/top.hookvip.pro#4]
### ⚠️ 重要阅读

- [X] 请确保你是LSPosed用户。
- [X] 请确保你已升级至 [最新的release版本](https://github.com/Xposed-Modules-Repo/top.hookvip.pro/releases/latest)。
- [X] 请确保你已在 [已有的issues](https://github.com/Xposed-Modules-Repo/top.hookvip.pro/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。

### 使用框架

LSPosed 1.9.2(7024)-Zygisk

### 设备信息

小米8 Android 10

### 应用名称

Fake Location

### 应用版本号

1.3.5 BETA 1598

### 问题描述

```text
1.3.5 BETA 1598版本使用时提示功能受限，并且使用旧版本会强制要求更新
但是Fuck For VIP模块似乎还能正常使用1598版本
```

### 问题截图/视频

![Screenshot_2024-12-31-12-40-23-095_com lerist fakelocation](https://github.com/user-attachments/assets/a5150354-ff88-4758-9641-b77d74349aa7)
顺便提供一下软件下载地址：
http://fakeloc.cc/app
https://github.com/Lerist/FakeLocation/releases

### LSPosed日志

----part 3 start----
[ 2024-12-31T12:52:05.385     1000:  2082:  2676 I/LSPosed-Bridge  ] [ INFO] 12-31 12:52:05 (PmsHookTarget28) @filterAppAccessLPr query from com.lerist.fakelocation
[ 2024-12-31T12:52:05.459    10358: 27239: 27239 I/LSPosedContext  ] top.hookvip.pro: [Fake Location -> LoadInfo]LoadInfo{loadPkg='com.lerist.fakelocation', modulePath='/data/app/top.hookvip.pro-H-JzQX_zec-lp-wkmeVCKw==/base.apk', Inject=protected final void com.stub.StubApp.attachBaseContext(android.content.Context), moduleVersionName='4.0.4', moduleVersionCode=20241215, hostVersionName='1.3.5 BETA', hostVersionCode=1598, crackHookInfo=[a60@6ceeda7], pluginAppInfos=[], pluginHookInfos=[], loadTime=1735620725042}

**Comment by lovejiuwu** [comment]
是否已登录账号

**Comment by XZHStudio** [comment]
> 是否已登录账号

还没有登录过

**Comment by lovejiuwu** [comment]
> > 是否已登录账号
> 
> 还没有登录过

请尝试随意登录一个账号

**Comment by XZHStudio** [comment]
![Screenshot_2024-12-31-14-21-17-767_com lerist fakelocation](https://github.com/user-attachments/assets/9255177e-8136-4243-9071-040ce690b72d)
成功了，谢谢
